### ISSUE TITLE
Imported UVs incorrect

### ISSUE THREAD

**Issue by sapper-trle** [nutti/blender-mqo#1]
Blender has UV origin at bottom left whereas Metasequoia has UV origin at top left.
V co-ordinates need to be transformed, i.e. to 1-V.

**Comment by nutti** [comment]
@sapper-trle 

Hi,
Sorry for late response.
I haven't notice this issue until now.

Thanks for your report!
I think this needs to be fixed.
By the way, your forked repository already fixed this issue and other issues.
https://github.com/sapper-trle/blender-mqo

If you don't mind, you may send pull request about there changes.
https://github.com/nutti/blender-mqo/pulls

What do you think about this idea?
If you not familiar with the pull request, I will teach you until your fixes are merged.

Thanks!

**Comment by nutti** [comment]
@sapper-trle 

Hi,

> your forked repository already fixed this issue and other issues.
> https://github.com/sapper-trle/blender-mqo

Is there comment about this?
I would like to include your patches to this repository if you don't mind.
Thanks for taking care of this add-on!

**Comment by sapper-trle** [comment]
OK if you just fix them.

**Comment by nutti** [comment]
@sapper-trle 

Thanks for your response!
BTW, do you familiar with Pull Request?
https://github.com/nutti/blender-mqo/pulls

If you do not familiar with this, I will manually merge patches.
Of course, I will add you to the author of this add-on if you don't mind.

**Comment by sapper-trle** [comment]
I am not really familiar with pull requests. Hope I did it right.

**Comment by nutti** [comment]
@sapper-trle 

Nice work!
I will check your pull request.
Thanks for your cooperate.

**Comment by nutti** [comment]
@sapper-trle 

Thanks for your great contribution!
I merged your changeset.
If you don't mind, I would like to add your name (sapper-trle) to [author](https://github.com/nutti/blender-mqo/blob/master/src/blender_mqo/__init__.py#L3).
Is it possible to add your name there?
You can also change the name to be added.

**Comment by nutti** [comment]
@sapper-trle 

I added your name to author of this add-on.

https://github.com/nutti/blender-mqo/commit/507af30b205860c19eaed8dce93812ece24c0935

Thanks for your contribution!
