### ISSUE TITLE
Error when clicking on Import MQO

### ISSUE THREAD

**Issue by LEOSAURE** [nutti/blender-mqo#10]
**System Information**
  
* OS: Windows 10
* Blender version: 2.93
* Add-on version: Don't know what it's is
* Metasequoia version: 1.1.0

**Expected behavior**  
I want know how i can solved this problem or if i can't solve myself, if you can't make a update about this error

**Description about the bug**  
When i clicking on Imoport MQO files, he says me i was a error in the line 874

**Screenshots/Files** [Optional]  
Here is a screen of the error : https://imgur.com/QvfmfI8

**Comment by nutti** [comment]
Thanks. I fixed this error.

The fixed version can be downloaded from the [master branch](https://github.com/nutti/blender-mqo/archive/refs/heads/master.zip).
