### ISSUE TITLE
doesn't show up in blender 2.90

### ISSUE THREAD

**Issue by BannedMan** [nutti/blender-mqo#11]
**System Information**
  
* OS: [e.g. Windows]
* Blender version: [e.g. 2.90.1]
* Add-on version: [e.g. 5.2]
* Metasequoia version: [e.g. 4.6.1]

**Expected behavior**  
*The behavior you expect about the feature you reported.*
to be downloaded and able to be checked in the addon edit

**Description about the bug**  
*The description about the bug.*
every time I try to install the Plugin, it says it has been loaded, but it never shows up in a blender, when trying to press the check button nor does the import choice

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*

**Additional comments** [Optional]
Pls, I want my Mqo model in blender..

**Comment by nutti** [comment]
@BannedMan 

> Add-on version: [e.g. 5.2]

What version you use?
This add-on has been released up to v1.1.
But you can use fixed version with unstable version.
https://github.com/nutti/blender-mqo/blob/master/docs/installation.md

**Comment by nutti** [comment]
@BannedMan 

Is there any update?

**Comment by BannedMan** [comment]
> @BannedMan
> 
> Is there any update?

sorry for the very long delayed reply. but the version master didnt work. but the v1.1 did. sorry for delay/ thanks i got it to work
