### ISSUE TITLE
Version 11.0 throw error on import start in Blender 2.93.4

### ISSUE THREAD

**Issue by zircher** [nutti/blender-mqo#12]
![image](https://user-images.githubusercontent.com/3857501/142902814-d9792498-44c6-49ca-9c56-ba9f01a2f8c7.png)

**Comment by nutti** [comment]
@zircher 

This bug has already been fixed by #10 .
Could you use the unstable version?
https://github.com/nutti/blender-mqo/blob/master/docs/installation.md
