### ISSUE TITLE
エクスポート/インポートボタンクリック時のエラー

### ISSUE THREAD

**Issue by Apartkktrain** [nutti/blender-mqo#13]
**System Information**
  
* OS: [Windows 10]
* Blender version: [3.0.1]
* Add-on version: [1.1]

**Expected behavior**  
エクスポート/インポートのボタンを押そうとすると発生する問題です。

**Description about the bug**  
```Python: Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender_mqo\ops.py", line 874, in invoke
    self.objects_to_import.clear()
AttributeError: '_PropertyDeferred' object has no attribute 'clear'

location: <unknown location>:-1

```

宜しくお願いします。

**Comment by nutti** [comment]
@Apartkktrain 

ご報告ありがとうございます。
こちらですが、unstable版では修正済みです。
以下のドキュメントからインストールし、エラーが消えるか確認いただけますでしょうか？
https://github.com/nutti/blender-mqo/blob/master/docs/installation.md

本件を修正したバージョン1.2を近々リリースしようと思います。

**Comment by nutti** [comment]
本修正を含んだVersion 1.2をリリースしました。
よろしければこちらもご利用ください。
