### ISSUE TITLE
exporter still same.

### ISSUE THREAD

**Issue by agsdoom** [nutti/blender-mqo#18]
better exporter like Obj  Select one Object  and it exports the object same size same cords not blank  same as orginal obj exporter file.
idk i have to many models to export to mqo format. but cant chose the models weigts cus to many models. :/ and materials. how should i export them ? when i cant select selected one to export ?

**Comment by nutti** [comment]
Post the expected behavior and related file (.mqo and .blend).
We can improve the importer/exporter from these information.

**Comment by agsdoom** [comment]
![image](https://user-images.githubusercontent.com/43580521/218363851-9d4d4b7d-bbe7-47ea-8ade-d98a3b805256.png)
![image](https://user-images.githubusercontent.com/43580521/218363891-33d845c7-5cfd-41c4-b4b0-bc29057e5bef.png)
![image](https://user-images.githubusercontent.com/43580521/218363933-db1de50c-ecb6-4887-bdb1-98226afb856a.png)

how am supose to export models lamfo ?

**Comment by agsdoom** [comment]
![image](https://user-images.githubusercontent.com/43580521/218367551-6dd25c9e-e73d-407b-ac94-743e739ff665.png)

i need also py script for mqo that deletes lines automaticaly :S

**Comment by nutti** [comment]
@agsdoom 

Please post the .mqo file or .blend file itself.

**Comment by agsdoom** [comment]
i have in blend over 1000 objects.. so i cant export them cus of  wierd list u got there dsnt matter anymore

**Comment by nutti** [comment]
We could not handle this issue any more if you don't post the actual file.
Your situation is too ambiguous to reproduce the error.

**Comment by nutti** [comment]
Any update?
