### ISSUE TITLE
Bone convertation

### ISSUE THREAD

**Issue by WinRaR4** [nutti/blender-mqo#19]
There's no realisation made for converting MQO model bones into blender bone format that attached to related vertex weights or any weight on them. It would be epic and priceful to code that into your already epic add-on for full compatibility and fully portable models with MQO file extension.
The thing is it's converting bones from MQO file to meshes in 2d pieces that have bone-reminding shapes. That's how it works for now.

Lots of hard work either, so if my feature request is hard/no need to accomplish, lemme know about that please!

With best regards and gratitude ;)

**Comment by nutti** [comment]
@WinRaR4 

Thanks for your request!
I think MQO model with bones is not free for metasequoia.

So, it is helpful for me that you share the simple .mqo file with bones.
From my understanding, the bone information will be saved to .mqx file.

If I could understand, I would try to add this feature.

**Comment by nutti** [comment]
@WinRaR4 

Any update?

**Comment by nutti** [comment]
Close this for now.

@WinRaR4 

Please ping us if this issue is available for you.
