### ISSUE TITLE
MQOZ file format

### ISSUE THREAD

**Issue by teephingJR** [nutti/blender-mqo#21]
Hello, I just wanted to know if you could also add the MQOZ file format, as now theres two different metasequoia file formats, that being MQO, and MQOZ. MQOZ is the newer file type, and I noticed that a lot of the metasequoia files I download are mostly MQOZ, and obviously I don't think the importer actually can import the newer file type. If it can import MQOZ, then I keep getting error messages whenever I try to import an MQOZ model, if that is the case, then please fix the issue, if not, please add the MQOZ file format, thank you!

**Comment by nutti** [comment]
@teephingJR 

This add-on supports .mqoz file format as well.
Could you give me a .mqoz file which you faced with the issue?

**Comment by nutti** [comment]
@teephingJR 

Any update?

**Comment by teephingJR** [comment]
Hey, sorry, I didn't see the original email, but I figured out a workaround
for the file not importing as mqoz, sorry for the inconvenience.

**Comment by nutti** [comment]
OK. I got it.
So, close this issue for now.
