### ISSUE TITLE
Texture Issue

### ISSUE THREAD

**Issue by JTCC1997** [nutti/blender-mqo#22]
**System Information**
  
* OS: [Windows 10]
* Blender version: [4.1]
* Add-on version: [1.3]
* Metasequoia version: [4.8.7b.]

Texture issue

First I imported the add-on to Blender and after I imported the model, and after I texturized it, it shows some non-coloured parts.

![blob](https://github.com/nutti/blender-mqo/assets/126607881/b82cefd7-d5fd-4f96-9c51-ce4d495ea226)

Please help me for fixing this issue.

**Comment by nutti** [comment]
@JTCC1997 

Sorry for the late response.
Could you give me some example mqo file which raises this error?

**Comment by JTCC1997** [comment]
This file.

**Comment by nutti** [comment]
@JTCC1997 

Any update?

**Comment by JTCC1997** [comment]
It's here (Original file download) :
https://www.maquettes-papier.net/forumenpapier/download/file.php?id=71240
Also there is a lot of other files : 
https://www.maquettes-papier.net/forumenpapier/download/file.php?id=69684
https://www.maquettes-papier.net/forumenpapier/download/file.php?id=49071
Sorry for being late a little bit.

**Comment by nutti** [comment]
@JTCC1997 

Thank you!
I will investigate your issue by using these files.

**Comment by JTCC1997** [comment]
No problem!
