### ISSUE TITLE
Crashing when importing certain MQO files

### ISSUE THREAD

**Issue by 54** [nutti/blender-mqo#4]
**System Information**
  
* OS: Windows 10 Education x86_64 (build: 19041.685)
* Blender version: 2.91
* Add-on version: latest version of the master branch (commit ae79211)
* Metasequoia version: 4.75a

**Description about the bug**  

Upon importing certain Metaseq projects prepared for RuneScape NPCs, Blender crashes immediately.

**Additional comments**

Example MQO file: https://yadi.sk/d/GFHotf_UqS3wSg 

Crash log: https://gist.github.com/54/3ddab317ada8dcdbe9b5a6af6add397d

Also, happy new year 😉

**Comment by nutti** [comment]
@54 

Thanks for your report.
Could you tell me the situation when the Blender was crashed.

In my environment, Blender was crashed when I changed the checkbox (meshes/materials to import) status in File Browser.

**Comment by 54** [comment]
Thanks for the quick response! Mine crashes upon selecting the file - I don't even have time to play with the checkboxes. 

Here's the latest log: https://gist.github.com/54/113d29280159b7fe9e400d2480edc1a6

**Comment by nutti** [comment]
@54 

I found why the Blender crash. Thanks for your information.
But I need a time to fix this bug.

**Comment by nutti** [comment]
@54 

If you don't mind, I can provide a temporary add-on.
The temporal add-on limits only subtle feature (import/export selection of material/mesh).
I think this limitation does not affect your use case.

**Comment by 54** [comment]
@nutti that would be appreciated! It might work fine for my uses

**Comment by nutti** [comment]
@54 

Thanks for understanding my proposal.

I uploaded the temporal version. This version fixed #5 as well as #4 on my environment.
Could you try it?
https://github.com/nutti/blender-mqo/archive/issue_4.zip

If this add-on is valid on your environment, I will merge this to main stream.

**Comment by nutti** [comment]
@54 

Sorry. I missed some patches in it.
Could you try it again?

https://github.com/nutti/blender-mqo/archive/issue_4.zip

**Comment by 54** [comment]
@nutti Awesome! That one did let me import the master chief model correctly. However, upon further testing, it seems to still explode with other projects. Here's a log: https://gist.github.com/54/6a849531a8ce6b31e5f5ad2a99882b66

And here's a demo project: https://yadi.sk/d/HtrYy0X_RU0-LQ

**Comment by nutti** [comment]
@54 

I found why the add-on crash.
But, the attached .mqo file violate MQO file format which includes invalid value.
Was the attached file created from Metasequoia?

**Comment by nutti** [comment]
@54 

I fixed your issue, and it works correctly in my environment.
Could you try this?

https://github.com/nutti/blender-mqo/archive/issue_4.zip

> Was the attached file created from Metasequoia?

Also, I want to know about this.

**Comment by 54** [comment]
@nutti Seems to work! Thanks a ton!

> But, the attached .mqo file violate MQO file format which includes invalid value.
> Was the attached file created from Metasequoia?
Really? Very weird. Yes, it was created in Metasequoia.

1. First, I imported this model into Blender, joined all the pieced, and then decimated it and exported it as an obj file https://www.models-resource.com/psp/evangelionshingekijoban3ndimpact/model/19222/
2. I created a new metaseq project based on my template used for rigging models to RuneScape (it's just a set of materials, basically) https://yadi.sk/d/uzJOQnT_06xbdQ
3. I painted the skins and set the weights on the vertices in order to rig the model
4. I saved the project in the old metaseq 2.2 format with "embed thumbnail" enabled

**Comment by nutti** [comment]
@54 

I think Metasequoia changed the format.
At first time, I implemented this add-on by referencing the official documents.
http://www.metaseq.net/en/format.html
From the document, there is a difference in vertex chunk format you attached.

Anyway, I merged the patch.
I think all issues were fixed now. So, I close this issue.
