### ISSUE TITLE
Crashing when exporting certain MQO files

### ISSUE THREAD

**Issue by 54** [nutti/blender-mqo#5]
**System Information**
  
* OS: Windows 10 Education x86_64 (build: 19041.685)
* Blender version: 2.91
* Add-on version: latest version of the master branch (commit ae79211)
* Metasequoia version: 4.75a

**Description about the bug**  

Upon exporting certain Metaseq projects prepared for RuneScape NPCs, Blender crashes immediately. Unlike in issue #4, this one at least does import properly.

**Additional comments**

Example MQO file: https://yadi.sk/d/xSiqWp7RK_4K1w

Crash log: https://gist.github.com/54/b8d6c11dd39979d4572f6a0e8eb53dc2

Also, happy new year 😉

**Comment by nutti** [comment]
This issue has already fixed by solving #4.
