### ISSUE TITLE
Import/export of vertex weights

### ISSUE THREAD

**Issue by 54** [nutti/blender-mqo#6]
**Description about the feature**  

It would be great if this add-on could import vertex weights set in Metasequoia into Blender vertex groups and vice versa.

**Are you willing to contribute about this feature. (Yes/No)** 

I am willing to donate money to this issue/assist if pointed in the right direction.

**Screenshots**

![weights metaseq](https://sis.sy/BitchyBitchySperg)

**Comment by mikanm** [comment]
much needed feature! would be nice to see this 👍

**Comment by nutti** [comment]
@54 

Thanks for your feature request.
It helps me a lot if you attach the example file with vertex weights.

**Comment by 54** [comment]
> It helps me a lot if you attach the example file with vertex weights.

@nutti Sure, here's an example MQO file with weights: https://yadi.sk/d/-OIBfD1Zil1Vzw

In the above link, all objects in the project share the same weights. However, as another test file, you can check out [this project](https://yadi.sk/d/g-kmjtIvJWdkBQ) which has multiple objects, each with different weights (see the "VSKIN1:", "VSKIN2:" objects - "TSKIN:" and "PRI:" will have no weights on this).

For my use case, in order to get the model to animate, I need to assign weights to the various vertices belonging to the different body parts of the model. 

I figure, it should be possible to map vertices with the same weights in metaseq to weighted vertex groups in Blender.

![rigging weights](http://sis.sy/PerverseCunningRoidcel)

**Comment by nutti** [comment]
@54 

Thanks. I will check it.
I don't have any experience about the vertex weight in both Blender and Metasequoia.
So I need a time to add this feature.

**Comment by nutti** [comment]
@54 

I have a question.
I think Blender handles the vertex weights by using the vertex group.
So, I'm going to add a vertex group which has weight values.
Does this method meet your requirement?

**Comment by nutti** [comment]
I have already finished adding the feature to import vertex weights as the vertex group.
If you want to try, you can download trial version.
https://github.com/nutti/blender-mqo/archive/issue_6.zip

I'm now tackling to add the feature to export.

**Comment by 54** [comment]
> I have almost finished adding the feature to import vertex weights as the vertex group.
> If you want to try, you can download trial version.
> https://github.com/nutti/blender-mqo/archive/issue_6.zip
> 
> I'm now tackling to add the feature to export.

Awesome! Seems to work well for MQO projects that have weights >0.00, but for models without weights, the plugin breaks. 

error log: https://gist.github.com/54/cd0c817647d2af5d612881a2a241e4d1
example MQO: https://yadi.sk/d/LxAJhSIAy4XVTw

> I have a question.
> I think Blender handles the vertex weights by using the vertex group.
> So, I'm going to add a vertex group which has weight values.
> Does this method meet your requirement?

Yep, that's the idea, but I think rather than one giant group, as the importer currently seems to do, it might be better import each collection of weights as a separate vertex group. 

As an example, if you look at the image I posted, the torso (the yellow material) has a weight of "8" (0.08), the right should has a weight of 25 (0.25), etc. 

It might be best to group everything that is weighted as 0.08 into its own group, everything that is weighted as 0.25 into its own group, and so on.

**Comment by nutti** [comment]
@54 

I fixed the bug, and added requested option.

Export feature will be added in this week.

**Comment by nutti** [comment]
@54 

I have almostly finished to add export feature.
Could you check if it works.

https://github.com/nutti/blender-mqo/archive/issue_6.zip

**Comment by nutti** [comment]
This feature is now merged to master branch.
Thanks for the feature requests @54 .

If there is a issue about this feature, feel free to make a new issue.
