### ISSUE TITLE
exporting system is so bad while exporting :G 

### ISSUE THREAD

**Issue by agsdoom** [nutti/blender-mqo#7]
exporting system is so bad  i have to find in over 2000 model pieces  while exporting :G  was thinking to use it but naah gonna skip that gotta weight in metaQ then :G  improvements should be selected and  and postion as it is orginal postion like obj file  but in metaQ  so it should export same postion same size  wuith materials  am unnable to find 
![image](https://user-images.githubusercontent.com/43580521/120674056-64cc8780-c49c-11eb-9510-2b816b4cfc80.png)   in here nohting :I fels bad ! :G  and model postion in metaQ is -90 or 90 :G  jeez 
![image](https://user-images.githubusercontent.com/43580521/120674330-a8bf8c80-c49c-11eb-9017-36393c9418f2.png)

and the normals are worst to  :G sad might get Select Obj file and export  as obj file should be as  mqo file with weights on it thts littlry waste of the  script due the bad exporting system srry! :D

**Comment by nutti** [comment]
@agsdoom 

Thanks for your feedback.
But sorry, I could not understand the problems you encountered from your report.

Is it possible to give me more information?

* The .blend data and .obj data which makes the issue 
* The expected behavior you want
* The version of blender-mqo add-on you used

**Comment by nutti** [comment]
@agsdoom 

Is there any following up about this issue?
If there is no response, I will close this issue within 1 week.

**Comment by agsdoom** [comment]
the issue is expoprt system

**Comment by agsdoom** [comment]
![image](https://user-images.githubusercontent.com/43580521/122123464-af53e980-ce36-11eb-94c8-51e5d27ec4dd.png)
i selected the file and i have to many models to need to export as mqo :I but yeah unnable to find nohting from this expor system kinda broken
![image](https://user-images.githubusercontent.com/43580521/122123556-c8f53100-ce36-11eb-85c3-8ed4c1ef4a4a.png)

**Comment by agsdoom** [comment]
i have like over 1000 files in there how am supose to find the correct file ?

**Comment by agsdoom** [comment]
![image](https://user-images.githubusercontent.com/43580521/122123786-1b365200-ce37-11eb-9c90-f9eca8446c81.png)
and even after exprted to mqo :I it looks like this no materials. and all messed up to  i guess i have to weight in metaQ since  this addon have no correct exporting mqo system :I

**Comment by nutti** [comment]
At first, Blender is not compatible to Metaseqoia, so we could not export full information on Blender.
But we could fix the add-on to close each other by using the reference model.
So, I need the below information to fix the issue as much I can.

* The .blend data and .obj data which makes the issue
* The expected behavior you want
* The version of blender-mqo add-on you used

**Comment by nutti** [comment]
This issue continues waiting status, so we will close for now.
Feel free to reopen this issue if there is a update.

**Comment by agsdoom** [comment]
used latest mqo add on ! :P
