### ISSUE TITLE
正しくインポートされない

### ISSUE THREAD

**Issue by Apartkktrain** [nutti/blender-mqo#8]
mqoをblenderに入れてみたかったので、導入してみたのですが、材質が反映されなかったり、インポート時にエラー文が大量に出ます。
![image](https://user-images.githubusercontent.com/64818647/121473375-8cbc6d80-c9fd-11eb-9061-977d0189a706.png)
どのようにすればよいでしょうか。
![image](https://user-images.githubusercontent.com/64818647/121473488-b7a6c180-c9fd-11eb-99e7-40d1b31eb5ed.png)

**Comment by Apartkktrain** [comment]
上記に関し、テクスチャが表示されないのはUnityの設定が原因でした。
その後Blender上では正常に表示できたのですが、その後fbxにエクスポートするとやはり画像がなくなり真っ白になってしまいます。画像とオブジェクトは同じ階層にあり、Unityで使用する際も一緒に同じ階層に移動しています。

**Comment by nutti** [comment]
@Apartkktrain 

MQO→Blenderのインポートについては、各ツールで使われているデータの違いにより完全に再現できないところがあります。
Blender→fbxに関してはこちらのアドオンでのサポート範囲外であるため、エクスポータの作者に別途確認してもらったほうが良いと思います。

なおインポート時のエラーに関して、現時点でも発生している状況でしょうか？
もしよろしければエラーが発生するmqoファイルを添付してもらえると助かります。

**Comment by nutti** [comment]
@Apartkktrain 

こちらの件、アップデートありますか？
もしなければ本Issueは数日以内にクローズします。

**Comment by nutti** [comment]
本件、回答がないため一度クローズします。
必要があれば再度オープンしてください。
